# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-03 01:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('pin_code', models.CharField(max_length=8)),
                ('duration', models.IntegerField(default=1800)),
                ('pub_date', models.DateTimeField(blank=True, null=True, verbose_name='date published')),
                ('isactive', models.BooleanField(default=False)),
                ('active_from', models.DateField(blank=True, null=True, verbose_name='active from')),
                ('active_till', models.DateField(blank=True, null=True, verbose_name='active till')),
                ('pass_date', models.DateTimeField(blank=True, null=True, verbose_name='date passed')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tests.Student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tests.Teacher')),
            ],
        ),
    ]
