# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-05 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_testlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='pin_code',
            field=models.CharField(editable=False, max_length=32),
        ),
    ]
