# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-05 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_auto_20170506_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
    ]
