# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-05 23:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_auto_20170506_1131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='pub_date',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='pass_date',
            new_name='date_passed',
        ),
    ]
