# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-06 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0007_auto_20170506_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testlog',
            name='photo',
            field=models.ImageField(upload_to='pics/'),
        ),
        migrations.AlterField(
            model_name='testlog',
            name='screenshot',
            field=models.ImageField(upload_to='pics/'),
        ),
    ]
