# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-20 08:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0008_auto_20170506_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='topic',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='testlog',
            name='photo',
            field=models.ImageField(editable=False, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='testlog',
            name='screenshot',
            field=models.ImageField(editable=False, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='testlog',
            name='test',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='tests.Test'),
        ),
    ]
