# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-23 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0009_auto_20170520_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testlog',
            name='screenshot',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='media/'),
        ),
    ]
