# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-30 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0010_auto_20170523_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='isactive',
        ),
        migrations.AlterField(
            model_name='test',
            name='pin_code',
            field=models.IntegerField(editable=False, max_length=10),
        ),
    ]
