# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-30 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0012_auto_20170530_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='active_from',
            field=models.DateField(verbose_name='active from'),
        ),
        migrations.AlterField(
            model_name='test',
            name='active_till',
            field=models.DateField(verbose_name='active till'),
        ),
    ]
