# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-30 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0014_auto_20170531_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='pin_code',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
