# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-02 22:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tests', '0015_auto_20170531_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='teacher',
        ),
        migrations.AddField(
            model_name='student',
            name='created_by',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='test',
            name='created_by',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
