# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 17:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0017_auto_20170711_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='passport_num',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='passport_scan',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='student',
            name='student_dob',
            field=models.DateField(default='2000-01-01', verbose_name='Students DoB'),
        ),
        migrations.AlterField(
            model_name='question',
            name='rec_duration',
            field=models.IntegerField(default=40),
        ),
        migrations.AlterField(
            model_name='student',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
