# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 12:37
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0018_auto_20170714_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='answer_marked',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='test',
            name='answer_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='question_text',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='test',
            name='teacher_notes',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
