# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0019_auto_20170715_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='grade',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2),
        ),
    ]
