# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0021_remove_test_teacher_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='grade',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
    ]
