# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 15:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0022_auto_20170718_1451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='rec_duration',
            new_name='duration',
        ),
    ]
