# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0023_auto_20170718_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='duration',
            field=models.IntegerField(default=40),
        ),
    ]
