# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 19:57
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0024_auto_20170718_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(default='', max_length=50)),
                ('type_blank', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='tests.QuestionType'),
        ),
    ]
