# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 14:38
from __future__ import unicode_literals

from django.db import migrations, models
import tests.models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0026_question_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100)),
                ('attachment', models.FileField(upload_to=tests.models.upload_attachments)),
            ],
            options={
                'ordering': ('file_name',),
            },
        ),
        migrations.RemoveField(
            model_name='question',
            name='files',
        ),
        migrations.AddField(
            model_name='question',
            name='attachments',
            field=models.ManyToManyField(blank=True, to='tests.Attachment'),
        ),
    ]
