# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 18:42
from __future__ import unicode_literals

from django.db import migrations, models
import tests.models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0027_auto_20170808_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='attachment',
            field=models.FileField(upload_to=tests.models.upload_attachments),
        ),
        migrations.AlterField(
            model_name='testlog',
            name='photo',
            field=models.ImageField(editable=False, upload_to=tests.models.get_testlogs_path),
        ),
        migrations.AlterField(
            model_name='testlog',
            name='screenshot',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to=tests.models.get_testlogs_path),
        ),
    ]
