# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 15:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0029_auto_20170809_1123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachment',
            old_name='attachment',
            new_name='path',
        ),
    ]
