# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0030_auto_20170809_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='passport_num',
            field=models.CharField(blank=True, default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='skype',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_dob',
            field=models.DateField(blank=True, default='2000-01-01', verbose_name='Students DoB'),
        ),
    ]
